version: "3"
services:
  redis:
    image: redis
    container_name: redis
    # command: --appendonly yes
    command: redis-server --requirepass 123456
    restart: always
    volumes:
      - ./data:/data
    ports: 
        - 6379:6379
